kind: pipeline
name: checkers
steps:
- name: compatibility
  image: nextcloudci/php7.3:latest
  environment:
    APP_NAME: deck
    CORE_BRANCH: stable20
    DB: sqlite
  commands:
    # Pre-setup steps
    - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
    - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
    - cd ../server
    # Code checker
    - ./occ app:check-code $APP_NAME -c strong-comparison
    - ./occ app:check-code $APP_NAME -c deprecation
    - cd apps/$APP_NAME/
- name: syntax-php7.2
  image: nextcloudci/php7.2:latest
  environment:
    APP_NAME: deck
    CORE_BRANCH: stable20
    DB: sqlite
  commands:
    - composer install
    - ./vendor/bin/parallel-lint --exclude ./vendor/ .
- name: syntax-php7.3
  image: nextcloudci/php7.3:php7.3-2
  environment:
    APP_NAME: deck
    CORE_BRANCH: stable20
    DB: sqlite
  commands:
    - composer install
    - ./vendor/bin/parallel-lint --exclude ./vendor/ .
- name: syntax-php7.4
  image: nextcloudci/php7.4:latest
  environment:
      APP_NAME: deck
      CORE_BRANCH: stable20
      DB: sqlite
  commands:
      - composer install
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: unit-php7.3
steps:
  - name: php7.3
    image: nextcloudci/php7.3:latest
    environment:
      APP_NAME: deck
      CORE_BRANCH: stable20
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - php occ app:enable deck
      - cd apps/$APP_NAME
      - composer install
      - phpunit -c tests/phpunit.xml --coverage-clover build/php-unit.coverage.xml
      - phpunit -c tests/phpunit.integration.xml --coverage-clover build/php-integration.coverage.xml
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
kind: pipeline
name: unit-php7.4
steps:
  - name: php7.4
    image: nextcloudci/php7.4:latest
    environment:
      APP_NAME: deck
      CORE_BRANCH: stable20
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - php occ app:enable deck
      - cd apps/$APP_NAME
      - composer install
      - phpunit -c tests/phpunit.xml --coverage-clover build/php-unit.coverage.xml
      - phpunit -c tests/phpunit.integration.xml --coverage-clover build/php-integration.coverage.xml
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: integration
steps:
  - name: integration
    image: nextcloudci/php7.3:latest
    environment:
      APP_NAME: deck
      CORE_BRANCH: stable20
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - php occ app:enable deck
      - cd apps/$APP_NAME
      - cd tests/integration
      - ./run.sh || true
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
