name: Federation integration tests

on:
  pull_request:
    paths:
      - '.github/workflows/integration-federation.yml'
      - 'appinfo/**'
      - 'lib/**'
      - 'templates/**'
      - 'tests/**'
      - 'composer.json'
      - 'composer.lock'
  push:
    branches:
      - main
      - master
      - stable*

permissions:
    contents: read

env:
  APP_NAME: deck

jobs:
  federation:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2']
        server-versions: ['master']

    name: php${{ matrix.php-versions }}-${{ matrix.server-versions }}

    steps:
      - name: Checkout server
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}
          submodules: true

      - name: Checkout app
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          path: apps/${{ env.APP_NAME }}

      - name: Checkout activity
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          repository: nextcloud/activity
          ref: ${{ matrix.server-versions }}
          path: apps/activity

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, apcu, gd
          ini-values:
            apc.enable_cli=on
          coverage: none

      - name: Set up dependencies
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i --no-dev

      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --admin-user admin --admin-pass admin
          ./occ config:system:set hashing_default_password --value=true --type=boolean
          ./occ config:system:set memcache.local --value="\\OC\\Memcache\\APCu"
          ./occ config:system:set memcache.distributed --value="\\OC\\Memcache\\APCu"
          cat config/config.php
          ./occ app:enable --force ${{ env.APP_NAME }}

      - name: Run federation behat tests
        working-directory: apps/${{ env.APP_NAME }}/tests/integration
        run: ./run-federation.sh

      - name: Print log
        if: always()
        run: |
          if [ -f data/nextcloud.log ]; then
            cat data/nextcloud.log
          else
            echo "Log file not found"
          fi
